### ISSUE TITLE
UserAdmin redirects to root when trying to open a certain page and there is no SystemUserSession for Session.Current

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/UserAdmin#7]

**Comment by miyconst** [comment]
Made a temporary fix: redirect to `/` only if user was signed in as `admin` and then signed out or signed in with a non admin user.

Still the UserAdmin app should be fully reworked to don't redirect at all. If user signs out while staying on a protected page then a red popup should appear, user may click go to home or login again.

@warpech what do you think?

**Comment by warpech** [comment]
Thanks!

I agree with the second paragraph. I am not a fan of redirects, because this can make the whole solution unusable if we have multiple apps with multiple permission levels.

I believe that there should be no links to something to what you don't have access. But if you still happen to be somewhere where you shouldn't be, it is enough to put a modest information about insufficient permissions.

This is related to https://github.com/Polyjuice/UserAdmin/issues/3, so I think we can close this issue if the temporary solution works

**Comment by miyconst** [comment]
Yes, the temporary fix works. Closing the issue.
